FROM node:18-alpine
LABEL AUTO_UPDATE="true"
WORKDIR /app
RUN apk add --update --no-cache python3 make g++ ffmpeg && rm -rf /var/cache/apk/*
COPY . /app
RUN npm ci
CMD npm run watch:serve
EXPOSE 3000
